# _config.yml
title: Gustavo - Desenvolvedor Full Stack
description: Meu perfil no GitHub e portfólio pessoal
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed

paginate: 5
paginate_path: "/pages/page:num/"