# _config.yml
title: Gustavo - Desenvolvedor Full Stack
description: Meu perfil no GitHub e portfólio pessoal
theme: jekyll-theme-minimal
plugins:
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed

paginate: 5
paginate_path: "/pages/page:num/"